"use client";
import { useMemo, useState } from "react";

type Module = { name: string; description: string; count: string; alert?: string };
type Department = { code: string; name: string; eyebrow: string; summary: string; color: string; modules: Module[] };

const departments: Record<string, Department> = {
  dashboard: { code: "IN", name: "Visão geral", eyebrow: "PAINEL EXECUTIVO", summary: "Acompanhe os principais indicadores e pendências da sua empresa.", color: "#2aa99a", modules: [] },
  rh: { code: "RH", name: "Recursos Humanos", eyebrow: "GESTÃO DE PESSOAS E CONFORMIDADE", summary: "Centralize colaboradores, documentos, equipamentos e licenças.", color: "#7657c8", modules: [
    { name: "Funcionários", description: "Admissão, pagamentos e contratos", count: "42 ativos" }, { name: "EPI", description: "Entregas, termos e vencimentos", count: "186 itens", alert: "3 assinaturas" }, { name: "Uniformes", description: "Entrega e reposição por colaborador", count: "74 entregas" }, { name: "Caminhões – Documentos", description: "CRLV, seguros e licenciamento", count: "8 veículos", alert: "1 próximo" }, { name: "Caminhões – Manutenção", description: "Histórico e notas de serviço", count: "23 serviços" }, { name: "Licenças da Empresa", description: "Alvará, ambiental e SIPROQUIM", count: "6 licenças", alert: "1 urgente" }, { name: "Recrutamento e Seleção", description: "Vagas, candidatos e etapas", count: "12 candidatos" },
  ]},
  logistica: { code: "LG", name: "Logística", eyebrow: "OPERAÇÃO E DISTRIBUIÇÃO", summary: "Planeje rotas, comprove entregas e cuide dos equipamentos.", color: "#2876e5", modules: [
    { name: "Rotas", description: "Planejamento e roteirização", count: "14 esta semana" }, { name: "Entregas", description: "Canhotos e comprovantes digitais", count: "128 no mês", alert: "5 pendentes" }, { name: "Equipamentos de Transporte", description: "Carrinhos, bombas e paleteiras", count: "31 ativos", alert: "2 manutenções" },
  ]},
  embalagem: { code: "EM", name: "Embalagem e Rotulagem", eyebrow: "PRODUÇÃO E RASTREABILIDADE", summary: "Gerencie artes, bombonas e insumos de embalagem.", color: "#d98d2e", modules: [
    { name: "Rótulos", description: "Artes e modelos por produto", count: "36 modelos" }, { name: "Controle de Bombonas", description: "Movimentação e rastreabilidade", count: "1.248 unidades" }, { name: "Estoque de Embalagem", description: "Saldo, consumo e estoque mínimo", count: "82 itens", alert: "4 em baixa" },
  ]},
  vendas: { code: "VD", name: "Vendas", eyebrow: "RELACIONAMENTO E RECEITA", summary: "Conduza clientes da oportunidade ao pós-venda.", color: "#1c9b77", modules: [
    { name: "Clientes", description: "Cadastro e histórico comercial", count: "284 ativos" }, { name: "Propostas e Orçamentos", description: "Pipeline, versões e aprovações", count: "R$ 326 mil", alert: "8 abertas" }, { name: "Pesquisa de Satisfação", description: "NPS e acompanhamento de respostas", count: "NPS 78" },
  ]},
  compras: { code: "CP", name: "Compras", eyebrow: "SUPRIMENTOS E FORNECEDORES", summary: "Controle cotações, pedidos e entradas fiscais.", color: "#d15c6d", modules: [
    { name: "Fornecedores", description: "Cadastro e avaliação", count: "67 homologados" }, { name: "Pedidos de Compra", description: "Solicitação, aprovação e entrega", count: "21 em aberto", alert: "4 aprovações" }, { name: "Notas Fiscais de Entrada", description: "Conferência fiscal e recebimento", count: "96 no mês" },
  ]},
  financeiro: { code: "FN", name: "Financeiro", eyebrow: "FLUXO DE CAIXA E RESULTADOS", summary: "Acompanhe recebíveis, obrigações e resultado gerencial.", color: "#2473ca", modules: [
    { name: "Notas Fiscais de Saída", description: "Emissão e acompanhamento", count: "R$ 487 mil" }, { name: "Boletos e Recebimentos", description: "Baixas, atrasos e conciliação", count: "18 em aberto", alert: "3 atrasados" }, { name: "Contas a Pagar", description: "Agenda e aprovações", count: "R$ 92 mil", alert: "6 esta semana" }, { name: "DRE e Relatórios", description: "Resultado e indicadores gerenciais", count: "Margem 24,7%" },
  ]},
};
const metrics = [{label:"Faturamento no mês",value:"R$ 487.250",note:"+12,4% vs. mês anterior",tone:"green"},{label:"Contas a receber",value:"R$ 128.400",note:"18 títulos em aberto",tone:"blue"},{label:"Entregas no prazo",value:"94,8%",note:"+2,1% neste mês",tone:"amber"},{label:"Pendências críticas",value:"7",note:"3 exigem ação hoje",tone:"red"}];
const recent = [["NF-008741","Indústria Norte Ltda.","Nota fiscal de saída","R$ 18.420,00","Pago"],["PC-002184","Embalagens São Paulo","Pedido de compra","R$ 7.890,00","Aprovação"],["ENT-00632","Química Brasil S.A.","Entrega","Hoje, 14:30","Em rota"],["PROP-0348","Grupo Horizonte","Proposta comercial","R$ 42.500,00","Negociação"]];

export default function Dashboard() {
  const [active,setActive]=useState("dashboard"),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[toast,setToast]=useState("");
  const current=departments[active]; const filteredModules=useMemo(()=>current.modules.filter(m=>`${m.name} ${m.description}`.toLowerCase().includes(query.toLowerCase())),[current,query]);
  function saveRecord(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setModal(false);setToast("Registro salvo com sucesso");setTimeout(()=>setToast(""),2600)}
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">Q</span><div><strong>Quimicativa</strong><small>Gestão integrada</small></div></div><nav aria-label="Navegação principal"><p className="nav-label">MENU PRINCIPAL</p>{Object.entries(departments).map(([key,item])=><button className={`nav-item ${active===key?"active":""}`} key={key} onClick={()=>{setActive(key);setQuery("")}}><span>{item.code}</span>{item.name}</button>)}</nav><div className="sidebar-footer"><div className="support-icon">?</div><div><strong>Central de suporte</strong><small>Fale com nossa equipe</small></div></div></aside><main className="main"><header className="topbar"><div className="search"><span>⌕</span><input aria-label="Pesquisar" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar clientes, notas, pedidos..."/><kbd>Ctrl K</kbd></div><div className="top-actions"><button className="icon-button" aria-label="Notificações" onClick={()=>setToast("Você tem 7 notificações pendentes")}>•<span className="bell">◌</span></button><div className="user"><span className="avatar">RM</span><div><strong>Rafael Martins</strong><small>Administrador</small></div><span>⌄</span></div></div></header><div className="content"><section className="welcome"><div><p className="eyebrow">{current.eyebrow}</p><h1>{active==="dashboard"?<>Bom dia, Rafael! <span>👋</span></>:current.name}</h1><p>{current.summary}</p></div><button className="primary-button" onClick={()=>setModal(true)}><span>+</span> Novo registro</button></section>{active==="dashboard"?<ExecutiveView onOpen={setActive}/>:<DepartmentView department={current} modules={filteredModules} query={query} onOpen={name=>setToast(`${name} aberto para consulta`)}/>}</div></main>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={saveRecord} onMouseDown={e=>e.stopPropagation()}><div className="modal-title"><div><p className="eyebrow">CADASTRO RÁPIDO</p><h2>Novo registro</h2></div><button type="button" onClick={()=>setModal(false)} aria-label="Fechar">×</button></div><label>Setor<select defaultValue={active==="dashboard"?"vendas":active}>{Object.entries(departments).filter(([k])=>k!=="dashboard").map(([k,d])=><option value={k} key={k}>{d.name}</option>)}</select></label><label>Título<input required placeholder="Ex.: Renovação de licença ambiental" autoFocus/></label><div className="form-row"><label>Responsável<input required placeholder="Nome"/></label><label>Prazo<input type="date" required/></label></div><label>Observações<textarea placeholder="Informações adicionais..." rows={3}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancelar</button><button className="primary-button">Salvar registro</button></div></form></div>}{toast&&<div className="toast" role="status"><span>✓</span>{toast}</div>}</div>;
}

function ExecutiveView({onOpen}:{onOpen:(key:string)=>void}){return <><section className="metrics" aria-label="Indicadores principais">{metrics.map(item=><article className="metric-card" key={item.label}><div className={`metric-icon ${item.tone}`}>{item.label.slice(0,2).toUpperCase()}</div><div className="metric-label">{item.label}<button aria-label="Mais opções">•••</button></div><strong>{item.value}</strong><small className={item.tone}>{item.note}</small></article>)}</section><section className="dashboard-grid"><FinancialPanel/><PendingPanel onOpen={onOpen}/></section><section className="panel recent-panel"><div className="panel-heading"><div><h2>Atividade recente</h2><p>Últimas movimentações entre todos os setores</p></div><button className="link-button">Ver relatório completo</button></div><div className="table-wrap"><table><thead><tr><th>Registro</th><th>Empresa / contato</th><th>Tipo</th><th>Valor / prazo</th><th>Status</th></tr></thead><tbody>{recent.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={cell}>{i===0?<strong>{cell}</strong>:i===4?<span className={`status s${row[4].length%4}`}>{cell}</span>:cell}</td>)}</tr>)}</tbody></table></div></section><section className="sector-shortcuts"><div className="section-title"><div><h2>Acesso rápido aos setores</h2><p>Visão consolidada de toda a empresa</p></div></div><div className="shortcut-grid">{Object.entries(departments).filter(([k])=>k!=="dashboard").map(([key,d])=><button key={key} onClick={()=>onOpen(key)}><span style={{background:d.color}}>{d.code}</span><div><strong>{d.name}</strong><small>{d.modules.length} módulos</small></div><b>›</b></button>)}</div></section></>}
function FinancialPanel(){return <article className="panel chart-panel"><div className="panel-heading"><div><h2>Visão financeira</h2><p>Faturamento x despesas nos últimos 6 meses</p></div><button className="select-button">6 meses ⌄</button></div><div className="chart-legend"><span><i className="dot revenue"/>Faturamento</span><span><i className="dot expense"/>Despesas</span></div><div className="chart"><div className="y-axis"><span>500k</span><span>400k</span><span>300k</span><span>200k</span><span>100k</span><span>0</span></div><div className="plot"><div className="gridlines"/><div className="area expense-area"/><div className="area revenue-area"/><div className="chart-months"><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span></div></div></div></article>}
function PendingPanel({onOpen}:{onOpen:(k:string)=>void}){const items=[["!","Licença ambiental","Vence em 5 dias","Urgente","red","rh"],["NF","Notas fiscais pendentes","4 aguardando conferência","Financeiro","amber","financeiro"],["EPI","Entrega de EPI","3 funcionários sem assinatura","RH","blue","rh"],["CV","Currículos para revisar","12 novos candidatos","Recrutamento","violet","rh"]];return <article className="panel pending-panel"><div className="panel-heading"><div><h2>Pendências</h2><p>Itens que precisam da sua atenção</p></div><button className="link-button">Ver todas</button></div><ul className="pending-list">{items.map(i=><li key={i[1]} onClick={()=>onOpen(i[5])}><span className={`task-icon ${i[4]}`}>{i[0]}</span><div><strong>{i[1]}</strong><small>{i[2]}</small></div><em className={`tag ${i[4]}`}>{i[3]}</em></li>)}</ul></article>}
function DepartmentView({department,modules,query,onOpen}:{department:Department;modules:Module[];query:string;onOpen:(n:string)=>void}){return <><section className="department-summary"><article><span>Registros ativos</span><strong>{department.modules.reduce((a,m)=>a+parseInt(m.count.replace(/\D/g,"")||"0"),0).toLocaleString("pt-BR")}</strong><small>em {department.modules.length} módulos</small></article><article><span>Pendências</span><strong>{department.modules.filter(m=>m.alert).length}</strong><small>itens para acompanhar</small></article><article><span>Conformidade</span><strong>96%</strong><small>processos em dia</small></article></section><div className="section-title"><div><h2>Módulos de {department.name}</h2><p>Selecione uma área para consultar ou gerenciar registros.</p></div><button className="select-button">Mais recentes ⌄</button></div><section className="module-grid">{modules.length?modules.map((m,i)=><button className="module-card" key={m.name} onClick={()=>onOpen(m.name)}><div className="module-top"><span className="module-code" style={{background:`${department.color}18`,color:department.color}}>{String(i+1).padStart(2,"0")}</span>{m.alert&&<em>{m.alert}</em>}</div><h3>{m.name}</h3><p>{m.description}</p><footer><strong>{m.count}</strong><b>›</b></footer></button>):<div className="empty-state"><span>⌕</span><h3>Nenhum módulo encontrado</h3><p>Não encontramos resultados para &ldquo;{query}&rdquo;.</p></div>}</section></>}
