"use client";

import { useEffect, useState } from "react";

type Summary = { label: string; revenueCents: number; grossProfitCents: number; deliveryCostCents: number; deliveryCount: number; deliveredWeightKg: number; averageProfitPerDeliveryCents: number; averageWeightKg: number; averagePaymentDays: number | null; marginPercent: number | null };
type Dimension = "customer" | "delivery" | "route" | "vehicle" | "region";
type Dimensions = Record<Dimension, Summary[]>;
const brl = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const dimensionLabels: Record<Dimension, string> = { customer: "Cliente", delivery: "Entrega", route: "Rota", vehicle: "Caminhão", region: "Região" };

export default function ProfitabilityCenter({ notify, canWrite }: { notify: (message: string) => void; canWrite: boolean }) {
  const [dimensions, setDimensions] = useState<Dimensions>({ customer: [], delivery: [], route: [], vehicle: [], region: [] }), [dimension, setDimension] = useState<Dimension>("customer"), [csv, setCsv] = useState(""), [saving, setSaving] = useState(false);
  const summary = dimensions[dimension];
  const load = () => fetch("/api/profitability").then(response => response.json()).then(data => setDimensions(data.dimensions ?? { customer: data.summary ?? [], delivery: [], route: [], vehicle: [], region: [] })).catch(() => undefined);
  useEffect(() => { load(); }, []);
  const importFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setCsv(await file.text()); };
  const submit = async () => { if (!csv.trim()) return notify("Selecione um CSV/TSV exportado da planilha."); setSaving(true); try { const response = await fetch("/api/profitability", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); notify(data.message); setCsv(""); await load(); } catch (error) { notify(error instanceof Error ? error.message : "Não foi possível importar a lucratividade"); } finally { setSaving(false); } };
  const allCustomers = dimensions.customer;
  return <div className="profitability-center">
    <div className="module-kpis"><article><span>Clientes consolidados</span><strong>{allCustomers.length}</strong></article><article><span>Faturamento importado</span><strong>{brl(allCustomers.reduce((sum, item) => sum + item.revenueCents, 0))}</strong></article><article><span>Lucro bruto importado</span><strong>{brl(allCustomers.reduce((sum, item) => sum + item.grossProfitCents, 0))}</strong></article></div>
    {canWrite && <section className="panel profit-import"><div className="panel-heading"><div><h2>Importar planilha de lucratividade</h2><p>Use CSV ou TSV e vincule por cliente, pedido, rota ou placa.</p></div></div><input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" onChange={importFile} /><small className="profit-help">Colunas: Cliente, Pedido, Rota, Placa, Região, Período, Faturamento, Lucro bruto, Custo entrega, Peso kg, Entregas e Prazo médio.</small><button className="primary-button" onClick={submit} disabled={saving || !csv}>{saving ? "Importando..." : "Importar dados"}</button></section>}
    <section className="panel profit-table"><div className="panel-heading"><div><h2>Rentabilidade comparativa</h2><p>Analise receita, lucro, custo e eficiência na dimensão escolhida.</p></div><label className="profit-dimension">Agrupar por<select value={dimension} onChange={event => setDimension(event.target.value as Dimension)}>{(Object.keys(dimensionLabels) as Dimension[]).map(key => <option key={key} value={key}>{dimensionLabels[key]}</option>)}</select></label></div>{summary.length ? <div className="table-wrap"><table><thead><tr><th>{dimensionLabels[dimension]}</th><th>Faturamento</th><th>Lucro bruto</th><th>Margem</th><th>Lucro / entrega</th><th>Custo entrega</th><th>Entregas</th><th>Peso médio</th><th>Prazo médio</th></tr></thead><tbody>{summary.map(item => <tr key={item.label}><td><strong>{item.label}</strong></td><td>{brl(item.revenueCents)}</td><td className={item.grossProfitCents >= 0 ? "profit-positive" : "profit-negative"}>{brl(item.grossProfitCents)}</td><td>{item.marginPercent !== null ? `${item.marginPercent.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%` : "—"}</td><td>{brl(item.averageProfitPerDeliveryCents)}</td><td>{brl(item.deliveryCostCents)}</td><td>{item.deliveryCount}</td><td>{item.averageWeightKg.toLocaleString("pt-BR", { maximumFractionDigits: 1 })} kg</td><td>{item.averagePaymentDays !== null ? `${item.averagePaymentDays.toLocaleString("pt-BR", { maximumFractionDigits: 1 })} dias` : "—"}</td></tr>)}</tbody></table></div> : <div className="logistics-empty">Não há dados vinculados para esta dimensão.</div>}</section>
  </div>;
}
