import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  role: text("role", { enum: ["ceo", "manager", "operator", "viewer"] }).notNull().default("viewer"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

export const records = sqliteTable("records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  department: text("department").notNull(),
  module: text("module").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  metadata: text("metadata").notNull().default("{}"),
  status: text("status").notNull().default("active"),
  priority: text("priority", { enum: ["low", "medium", "high", "critical"] }).notNull().default("medium"),
  ownerId: text("owner_id").references(() => users.id),
  dueDate: integer("due_date", { mode: "timestamp" }),
  amountCents: integer("amount_cents"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_records_department_module").on(table.department, table.module), index("idx_records_status_due_date").on(table.status, table.dueDate)]);

export const intakeBatches = sqliteTable("intake_batches", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  department: text("department").notNull(),
  module: text("module").notNull(),
  responsible: text("responsible").notNull(),
  physicalLocation: text("physical_location").notNull(),
  expectedDocuments: integer("expected_documents").notNull().default(1),
  expectedPages: integer("expected_pages").notNull().default(1),
  receivedDocuments: integer("received_documents").notNull().default(0),
  receivedPages: integer("received_pages").notNull().default(0),
  divergences: text("divergences").notNull().default(""),
  status: text("status").notNull().default("open"),
  createdBy: text("created_by").notNull().references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_batches_department_status").on(table.department, table.status)]);

export const files = sqliteTable("files", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  recordId: integer("record_id").notNull().references(() => records.id),
  storageKey: text("storage_key").notNull().unique(),
  filename: text("filename").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  department: text("department").notNull().default("inbox"),
  module: text("module").notNull().default("Caixa de entrada"),
  documentType: text("document_type").notNull().default("Documento geral"),
  referenceDate: integer("reference_date", { mode: "timestamp" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  notes: text("notes"),
  status: text("status").notNull().default("review"),
  checksum: text("checksum"),
  batchCode: text("batch_code"),
  physicalLocation: text("physical_location"),
  confidentiality: text("confidentiality").notNull().default("internal"),
  pageCount: integer("page_count").notNull().default(1),
  version: integer("version").notNull().default(1),
  validationChecklist: text("validation_checklist").notNull().default("{}"),
  ocrText: text("ocr_text"),
  reviewedBy: text("reviewed_by").references(() => users.id),
  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
  rejectionReason: text("rejection_reason"),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  uploadedBy: text("uploaded_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_files_record_id").on(table.recordId), index("idx_files_department_module").on(table.department, table.module), index("idx_files_status_expires_at").on(table.status, table.expiresAt), uniqueIndex("uidx_files_checksum").on(table.checksum)]);

export const auditLog = sqliteTable("audit_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  actorId: text("actor_id").references(() => users.id),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  details: text("details"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_audit_entity").on(table.entityType, table.entityId), index("idx_audit_created_at").on(table.createdAt)]);

export const products = sqliteTable("products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  category: text("category").notNull().default("Outros"),
  concentration: text("concentration"),
  unNumber: text("un_number"),
  hazardClass: text("hazard_class"),
  signalWord: text("signal_word"),
  hPhrases: text("h_phrases").notNull().default("[]"),
  pPhrases: text("p_phrases").notNull().default("[]"),
  controlled: integer("controlled").notNull().default(0),
  controlAgency: text("control_agency"),
  flammable: integer("flammable").notNull().default(0),
  storage: text("storage"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_products_category").on(table.category), index("idx_products_status").on(table.status)]);

export const lots = sqliteTable("lots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productId: integer("product_id").notNull().references(() => products.id),
  lotNumber: text("lot_number").notNull(),
  manufactureDate: integer("manufacture_date", { mode: "timestamp" }),
  expiryDate: integer("expiry_date", { mode: "timestamp" }),
  quantity: integer("quantity").notNull().default(0),
  unit: text("unit").notNull().default("un"),
  location: text("location"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_lots_product_id").on(table.productId), index("idx_lots_expiry_date").on(table.expiryDate)]);

export const suppliers = sqliteTable("suppliers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyName: text("company_name").notNull(),
  cnpj: text("cnpj").notNull().unique(),
  stateRegistration: text("state_registration"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  certificates: text("certificates").notNull().default("[]"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_suppliers_status").on(table.status)]);

export const fispq = sqliteTable("fispq", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productId: integer("product_id").notNull().references(() => products.id),
  version: text("version").notNull().default("1"),
  issueDate: integer("issue_date", { mode: "timestamp" }),
  validityDate: integer("validity_date", { mode: "timestamp" }),
  fileKey: text("file_key"),
  fileName: text("file_name"),
  fileSize: integer("file_size"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_fispq_product_id").on(table.productId), index("idx_fispq_validity_date").on(table.validityDate)]);

export const licenses = sqliteTable("licenses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  licenseType: text("license_type").notNull(),
  issuingAgency: text("issuing_agency").notNull(),
  number: text("number").notNull(),
  validityDate: integer("validity_date", { mode: "timestamp" }),
  scope: text("scope"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_licenses_validity_date").on(table.validityDate), index("idx_licenses_status").on(table.status)]);
