import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  role: text("role", { enum: ["ceo", "manager", "operator", "viewer"] }).notNull().default("viewer"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

export const records = sqliteTable("records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  department: text("department").notNull(),
  module: text("module").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  metadata: text("metadata").notNull().default("{}"),
  status: text("status").notNull().default("active"),
  priority: text("priority", { enum: ["low", "medium", "high", "critical"] }).notNull().default("medium"),
  ownerId: text("owner_id").references(() => users.id),
  dueDate: integer("due_date", { mode: "timestamp" }),
  amountCents: integer("amount_cents"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_records_department_module").on(table.department, table.module), index("idx_records_status_due_date").on(table.status, table.dueDate)]);

export const intakeBatches = sqliteTable("intake_batches", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  department: text("department").notNull(),
  module: text("module").notNull(),
  responsible: text("responsible").notNull(),
  physicalLocation: text("physical_location").notNull(),
  expectedDocuments: integer("expected_documents").notNull().default(1),
  expectedPages: integer("expected_pages").notNull().default(1),
  receivedDocuments: integer("received_documents").notNull().default(0),
  receivedPages: integer("received_pages").notNull().default(0),
  divergences: text("divergences").notNull().default(""),
  status: text("status").notNull().default("open"),
  createdBy: text("created_by").notNull().references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_batches_department_status").on(table.department, table.status)]);

export const files = sqliteTable("files", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  recordId: integer("record_id").notNull().references(() => records.id),
  storageKey: text("storage_key").notNull().unique(),
  filename: text("filename").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  department: text("department").notNull().default("inbox"),
  module: text("module").notNull().default("Caixa de entrada"),
  documentType: text("document_type").notNull().default("Documento geral"),
  referenceDate: integer("reference_date", { mode: "timestamp" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  notes: text("notes"),
  status: text("status").notNull().default("review"),
  checksum: text("checksum"),
  batchCode: text("batch_code"),
  physicalLocation: text("physical_location"),
  confidentiality: text("confidentiality").notNull().default("internal"),
  pageCount: integer("page_count").notNull().default(1),
  version: integer("version").notNull().default(1),
  validationChecklist: text("validation_checklist").notNull().default("{}"),
  ocrText: text("ocr_text"),
  reviewedBy: text("reviewed_by").references(() => users.id),
  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
  rejectionReason: text("rejection_reason"),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  uploadedBy: text("uploaded_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_files_record_id").on(table.recordId), index("idx_files_department_module").on(table.department, table.module), index("idx_files_status_expires_at").on(table.status, table.expiresAt), uniqueIndex("uidx_files_checksum").on(table.checksum)]);

export const auditLog = sqliteTable("audit_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  actorId: text("actor_id").references(() => users.id),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  details: text("details"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_audit_entity").on(table.entityType, table.entityId), index("idx_audit_created_at").on(table.createdAt)]);

export const products = sqliteTable("products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  category: text("category").notNull().default("Outros"),
  concentration: text("concentration"),
  unNumber: text("un_number"),
  hazardClass: text("hazard_class"),
  signalWord: text("signal_word"),
  hPhrases: text("h_phrases").notNull().default("[]"),
  pPhrases: text("p_phrases").notNull().default("[]"),
  controlled: integer("controlled").notNull().default(0),
  controlAgency: text("control_agency"),
  flammable: integer("flammable").notNull().default(0),
  storage: text("storage"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_products_category").on(table.category), index("idx_products_status").on(table.status)]);

export const lots = sqliteTable("lots", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productId: integer("product_id").notNull().references(() => products.id),
  lotNumber: text("lot_number").notNull(),
  manufactureDate: integer("manufacture_date", { mode: "timestamp" }),
  expiryDate: integer("expiry_date", { mode: "timestamp" }),
  quantity: integer("quantity").notNull().default(0),
  unit: text("unit").notNull().default("un"),
  location: text("location"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_lots_product_id").on(table.productId), index("idx_lots_expiry_date").on(table.expiryDate)]);

export const suppliers = sqliteTable("suppliers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyName: text("company_name").notNull(),
  cnpj: text("cnpj").notNull().unique(),
  stateRegistration: text("state_registration"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  certificates: text("certificates").notNull().default("[]"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_suppliers_status").on(table.status)]);

export const fispq = sqliteTable("fispq", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  productId: integer("product_id").notNull().references(() => products.id),
  version: text("version").notNull().default("1"),
  issueDate: integer("issue_date", { mode: "timestamp" }),
  validityDate: integer("validity_date", { mode: "timestamp" }),
  fileKey: text("file_key"),
  fileName: text("file_name"),
  fileSize: integer("file_size"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_fispq_product_id").on(table.productId), index("idx_fispq_validity_date").on(table.validityDate)]);

export const licenses = sqliteTable("licenses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  licenseType: text("license_type").notNull(),
  issuingAgency: text("issuing_agency").notNull(),
  number: text("number").notNull(),
  validityDate: integer("validity_date", { mode: "timestamp" }),
  scope: text("scope"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_licenses_validity_date").on(table.validityDate), index("idx_licenses_status").on(table.status)]);

export const customers = sqliteTable("customers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyName: text("company_name").notNull(),
  tradingName: text("trading_name"),
  document: text("document").notNull().default(""),
  stateRegistration: text("state_registration"),
  street: text("street"),
  number: text("number"),
  complement: text("complement"),
  district: text("district"),
  city: text("city"),
  state: text("state"),
  zipCode: text("zip_code"),
  receivingWindow: text("receiving_window").notNull().default(""),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  segment: text("segment"),
  lgpdBasis: text("lgpd_basis").notNull().default("Execução de contrato"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_customers_status").on(table.status), index("idx_customers_document").on(table.document)]);

export const orders = sqliteTable("orders", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  number: text("number").notNull().default("").unique(),
  customerId: integer("customer_id").notNull().references(() => customers.id),
  orderDate: integer("order_date", { mode: "timestamp" }),
  deliveryDate: integer("delivery_date", { mode: "timestamp" }),
  paymentTerms: text("payment_terms").notNull().default(""),
  status: text("status").notNull().default("draft"),
  notes: text("notes"),
  sourcePayload: text("source_payload"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_orders_customer_id").on(table.customerId), index("idx_orders_status").on(table.status), index("idx_orders_created_at").on(table.createdAt)]);

export const orderItems = sqliteTable("order_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  orderId: integer("order_id").notNull().references(() => orders.id),
  productId: integer("product_id").notNull().references(() => products.id),
  productName: text("product_name").notNull(),
  quantity: real("quantity").notNull().default(0),
  unit: text("unit").notNull().default("L"),
  unitPriceCents: integer("unit_price_cents").notNull().default(0),
  packageCount: real("package_count").notNull().default(0),
  packageType: text("package_type").notNull().default(""),
  packageUnitWeightKg: real("package_unit_weight_kg").notNull().default(0),
  weightKg: real("weight_kg").notNull().default(0),
  volumeM3: real("volume_m3").notNull().default(0),
  lotNumber: text("lot_number"),
  notes: text("notes"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_order_items_order_id").on(table.orderId), index("idx_order_items_product_id").on(table.productId)]);

export const orderDocuments = sqliteTable("order_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  orderId: integer("order_id").notNull().references(() => orders.id),
  orderItemId: integer("order_item_id").references(() => orderItems.id),
  kind: text("kind").notNull(),
  storageKey: text("storage_key").notNull().unique(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  metadata: text("metadata").notNull().default("{}"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  uploadedBy: text("uploaded_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_order_docs_order_kind").on(table.orderId, table.kind), index("idx_order_docs_item").on(table.orderItemId)]);

export const vehicles = sqliteTable("vehicles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  plate: text("plate").notNull().unique(),
  renavam: text("renavam"),
  chassis: text("chassis"),
  brand: text("brand").notNull().default(""),
  model: text("model").notNull(),
  modelYear: integer("model_year"),
  vehicleType: text("vehicle_type").notNull().default("Caminhão"),
  capacityKg: integer("capacity_kg"),
  capacityM3: real("capacity_m3"),
  odometerKm: integer("odometer_km").notNull().default(0),
  maintIntervalKm: integer("maint_interval_km"),
  maintIntervalMonths: integer("maint_interval_months"),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_vehicles_status").on(table.status), index("idx_vehicles_plate").on(table.plate)]);

export const vehicleDocuments = sqliteTable("vehicle_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  docType: text("doc_type").notNull(),
  number: text("number"),
  issuingBody: text("issuing_body"),
  issueDate: integer("issue_date", { mode: "timestamp" }),
  expiryDate: integer("expiry_date", { mode: "timestamp" }),
  storageKey: text("storage_key").unique(),
  fileName: text("file_name"),
  contentType: text("content_type"),
  sizeBytes: integer("size_bytes"),
  notes: text("notes"),
  uploadedBy: text("uploaded_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_vehicle_docs_vehicle").on(table.vehicleId), index("idx_vehicle_docs_expiry").on(table.expiryDate)]);

export const vehicleMaintenance = sqliteTable("vehicle_maintenance", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  maintType: text("maint_type").notNull().default("Preventiva"),
  serviceDate: integer("service_date", { mode: "timestamp" }).notNull(),
  odometerKm: integer("odometer_km").notNull().default(0),
  description: text("description"),
  supplier: text("supplier"),
  costCents: integer("cost_cents").notNull().default(0),
  nextDueKm: integer("next_due_km"),
  nextDueDate: integer("next_due_date", { mode: "timestamp" }),
  status: text("status").notNull().default("completed"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_vehicle_maint_vehicle").on(table.vehicleId), index("idx_vehicle_maint_date").on(table.serviceDate)]);

export const drivers = sqliteTable("drivers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  cpf: text("cpf").unique(),
  phone: text("phone"),
  licenseNumber: text("license_number"),
  licenseCategory: text("license_category"),
  licenseExpiry: integer("license_expiry", { mode: "timestamp" }),
  moppExpiry: integer("mopp_expiry", { mode: "timestamp" }),
  status: text("status").notNull().default("active"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_drivers_status").on(table.status), index("idx_drivers_expiry").on(table.licenseExpiry, table.moppExpiry)]);

export const routes = sqliteTable("routes", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  driverId: integer("driver_id").references(() => drivers.id),
  driverName: text("driver_name").notNull().default(""),
  routeDate: integer("route_date", { mode: "timestamp" }).notNull(),
  originAddress: text("origin_address").notNull().default(""),
  status: text("status").notNull().default("draft"),
  plannedKm: real("planned_km").notNull().default(0),
  estimatedCostCents: integer("estimated_cost_cents").notNull().default(0),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_routes_vehicle_date").on(table.vehicleId, table.routeDate), index("idx_routes_driver_date").on(table.driverId, table.routeDate), index("idx_routes_status").on(table.status)]);

export const routeStops = sqliteTable("route_stops", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  routeId: integer("route_id").notNull().references(() => routes.id),
  orderId: integer("order_id").notNull().references(() => orders.id),
  sequence: integer("sequence").notNull(),
  status: text("status").notNull().default("pending"),
  addressSnapshot: text("address_snapshot").notNull().default(""),
  weightKg: real("weight_kg").notNull().default(0),
  packageSummary: text("package_summary").notNull().default(""),
  volumeM3: real("volume_m3").notNull().default(0),
  receivingWindow: text("receiving_window").notNull().default(""),
  deliveredAt: integer("delivered_at", { mode: "timestamp" }),
  notes: text("notes"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_route_stops_route_sequence").on(table.routeId, table.sequence), index("idx_route_stops_order").on(table.orderId)]);

export const erpIntegrations = sqliteTable("erp_integrations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  provider: text("provider").notNull().default("REST"),
  baseUrl: text("base_url").notNull(),
  ordersPath: text("orders_path").notNull().default("/orders"),
  apiToken: text("api_token"),
  secretApiToken: text("secret_api_token"),
  customersPath: text("customers_path").notNull().default("/clientes"),
  goodsReceiptsPath: text("goods_receipts_path").notNull().default("/entradas"),
  invoicesPath: text("invoices_path").notNull().default("/notas-fiscais"),
  receivablesPath: text("receivables_path").notNull().default("/contas-a-receber"),
  active: integer("active").notNull().default(0),
  lastSyncAt: integer("last_sync_at", { mode: "timestamp" }),
  lastSyncStatus: text("last_sync_status"),
  lastSyncMessage: text("last_sync_message"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const profitabilityEntries = sqliteTable("profitability_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  orderId: integer("order_id").references(() => orders.id),
  customerId: integer("customer_id").references(() => customers.id),
  routeId: integer("route_id").references(() => routes.id),
  vehicleId: integer("vehicle_id").references(() => vehicles.id),
  region: text("region").notNull().default(""),
  period: integer("period", { mode: "timestamp" }).notNull(),
  revenueCents: integer("revenue_cents").notNull().default(0),
  grossProfitCents: integer("gross_profit_cents").notNull().default(0),
  deliveryCostCents: integer("delivery_cost_cents").notNull().default(0),
  deliveredWeightKg: real("delivered_weight_kg").notNull().default(0),
  deliveryCount: integer("delivery_count").notNull().default(1),
  averagePaymentDays: real("average_payment_days"),
  source: text("source").notNull().default("manual"),
  sourceKey: text("source_key").unique(),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

export const routeEvents = sqliteTable("route_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  routeId: integer("route_id").notNull().references(() => routes.id),
  stopId: integer("stop_id").references(() => routeStops.id),
  eventType: text("event_type").notNull(),
  occurredAt: integer("occurred_at", { mode: "timestamp" }).notNull(),
  odometerKm: real("odometer_km"),
  fuelLiters: real("fuel_liters"),
  notes: text("notes"),
  createdBy: text("created_by").references(() => users.id),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, table => [index("idx_route_events_route_time").on(table.routeId, table.occurredAt), index("idx_route_events_stop").on(table.stopId)]);
