import { NextResponse } from "next/server";
import { getD1 } from "../../../db";
import { getActor } from "../authz";

type ProfitRank = { label: string; revenue_cents: number; profit_cents: number; deliveries: number };
type RoutePerformance = { id: number; name: string; plate: string; loaded_kg: number; capacity_kg: number | null; occupancy: number | null; profit_cents: number; deliveries: number };
type VehiclePerformance = { plate: string; routes: number; average_occupancy: number; profit_cents: number };

export async function GET() {
  if (!(await getActor())) return NextResponse.json({ error: "Acesso não autorizado" }, { status: 401 });
  const db = getD1(), now = Math.floor(Date.now() / 1000), day = 86400, weekStart = now - 7 * day, monthStart = now - 30 * day;
  const [week, month, fleet, profitability, customerProfit, routePerformance, vehiclePerformance] = await Promise.all([
    db.prepare("SELECT COUNT(DISTINCT o.customer_id) AS customers,COUNT(DISTINCT s.id) AS deliveries,COALESCE(SUM(s.weight_kg),0) AS weight_kg FROM route_stops s JOIN routes r ON r.id=s.route_id JOIN orders o ON o.id=s.order_id WHERE s.status='completed' AND COALESCE(s.delivered_at,r.route_date)>=?").bind(weekStart).first<{ customers: number; deliveries: number; weight_kg: number }>(),
    db.prepare("SELECT COALESCE(SUM(oi.quantity*oi.unit_price_cents),0) AS revenue_cents,COUNT(DISTINCT o.id) AS orders FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.status<>'cancelled' AND o.order_date>=?").bind(monthStart).first<{ revenue_cents: number; orders: number }>(),
    db.prepare("SELECT COUNT(*) AS routes,COALESCE(AVG(CASE WHEN v.capacity_kg>0 THEN loaded.weight_kg*100.0/v.capacity_kg END),0) AS avg_occupancy,SUM(CASE WHEN v.capacity_kg>0 AND loaded.weight_kg*100.0/v.capacity_kg<50 THEN 1 ELSE 0 END) AS low_occupancy FROM routes r JOIN vehicles v ON v.id=r.vehicle_id JOIN (SELECT route_id,SUM(weight_kg) AS weight_kg FROM route_stops GROUP BY route_id) loaded ON loaded.route_id=r.id WHERE r.route_date>=?").bind(monthStart).first<{ routes: number; avg_occupancy: number; low_occupancy: number }>(),
    db.prepare("SELECT COALESCE(SUM(gross_profit_cents),0) AS profit_cents,COALESCE(SUM(delivery_cost_cents),0) AS delivery_cost_cents FROM profitability_entries WHERE period>=?").bind(monthStart).first<{ profit_cents: number; delivery_cost_cents: number }>(),
    db.prepare("SELECT CASE WHEN c.company_name IS NOT NULL AND c.company_name<>'' THEN c.company_name WHEN p.region<>'' THEN p.region ELSE 'Sem classificação' END AS label,SUM(p.revenue_cents) AS revenue_cents,SUM(p.gross_profit_cents) AS profit_cents,SUM(p.delivery_count) AS deliveries FROM profitability_entries p LEFT JOIN customers c ON c.id=p.customer_id WHERE p.period>=? GROUP BY label").bind(monthStart).all<ProfitRank>(),
    db.prepare("SELECT r.id,r.name,v.plate,v.capacity_kg,COALESCE(load.loaded_kg,0) AS loaded_kg,CASE WHEN v.capacity_kg>0 THEN COALESCE(load.loaded_kg,0)*100.0/v.capacity_kg END AS occupancy,COALESCE(profit.profit_cents,0) AS profit_cents,COALESCE(load.deliveries,0) AS deliveries FROM routes r JOIN vehicles v ON v.id=r.vehicle_id LEFT JOIN (SELECT route_id,SUM(weight_kg) AS loaded_kg,COUNT(*) AS deliveries FROM route_stops GROUP BY route_id) load ON load.route_id=r.id LEFT JOIN (SELECT route_id,SUM(gross_profit_cents) AS profit_cents FROM profitability_entries WHERE period>=? GROUP BY route_id) profit ON profit.route_id=r.id WHERE r.route_date>=? ORDER BY r.route_date DESC,r.id DESC").bind(monthStart, monthStart).all<RoutePerformance>(),
    db.prepare("SELECT v.plate,COUNT(DISTINCT r.id) AS routes,COALESCE(AVG(CASE WHEN v.capacity_kg>0 THEN load.loaded_kg*100.0/v.capacity_kg END),0) AS average_occupancy,COALESCE(MAX(profit.profit_cents),0) AS profit_cents FROM vehicles v JOIN routes r ON r.vehicle_id=v.id LEFT JOIN (SELECT route_id,SUM(weight_kg) AS loaded_kg FROM route_stops GROUP BY route_id) load ON load.route_id=r.id LEFT JOIN (SELECT vehicle_id,SUM(gross_profit_cents) AS profit_cents FROM profitability_entries WHERE period>=? GROUP BY vehicle_id) profit ON profit.vehicle_id=v.id WHERE r.route_date>=? GROUP BY v.id,v.plate ORDER BY average_occupancy DESC").bind(monthStart, monthStart).all<VehiclePerformance>(),
  ]);
  const customers = customerProfit.results.map(item => ({ label: item.label, revenueCents: item.revenue_cents, profitCents: item.profit_cents, deliveries: item.deliveries })).sort((a, b) => b.profitCents - a.profitCents);
  const routes = routePerformance.results.map(item => ({ id: item.id, name: item.name, plate: item.plate, loadedKg: item.loaded_kg, capacityKg: item.capacity_kg, occupancy: item.occupancy === null ? null : Math.round(item.occupancy), profitCents: item.profit_cents, deliveries: item.deliveries }));
  const vehicles = vehiclePerformance.results.map(item => ({ plate: item.plate, routes: item.routes, averageOccupancy: Math.round(item.average_occupancy), profitCents: item.profit_cents }));
  return NextResponse.json({ period: { weekStart, monthStart, generatedAt: now }, week: { customers: week?.customers ?? 0, deliveries: week?.deliveries ?? 0, weightKg: week?.weight_kg ?? 0 }, month: { revenueCents: Math.round(month?.revenue_cents ?? 0), orders: month?.orders ?? 0, profitCents: profitability?.profit_cents ?? 0, deliveryCostCents: profitability?.delivery_cost_cents ?? 0 }, fleet: { routes: fleet?.routes ?? 0, averageOccupancy: Math.round(fleet?.avg_occupancy ?? 0), lowOccupancyRoutes: fleet?.low_occupancy ?? 0 }, rankings: { mostProfitableCustomers: customers.slice(0, 5), leastProfitableCustomers: [...customers].sort((a, b) => a.profitCents - b.profitCents).slice(0, 5), vehicles, routes }, alerts: { lowOccupancyRoutes: routes.filter(route => route.occupancy !== null && route.occupancy < 50).slice(0, 5), lowProfitRoutes: routes.filter(route => route.profitCents <= 0).sort((a, b) => a.profitCents - b.profitCents).slice(0, 5) } });
}
